# Generated by Django 3.2.4 on 2021-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210605_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
