# Generated by Django 3.2.4 on 2021-06-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id'], 'verbose_name': 'Вопрос/Ответ', 'verbose_name_plural': 'Вопрос(-ов)/Ответ(-ов)'},
        ),
    ]
