# Generated by Django 3.2.4 on 2021-06-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_faq_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id'], 'verbose_name': 'Услуга(-у)', 'verbose_name_plural': 'Услуг(-и)'},
        ),
    ]
