# Generated by Django 3.2.4 on 2021-06-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('position', models.CharField(max_length=255, verbose_name='Должность/хобби')),
                ('phrase', models.CharField(max_length=511, verbose_name='Высказывание')),
                ('photo', models.ImageField(upload_to='photos/clients/')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзыв(-ов)',
                'ordering': ['id', 'name'],
            },
        ),
    ]
