# Generated by Django 3.2.4 on 2021-06-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='phrase',
            field=models.TextField(max_length=511, verbose_name='Высказывание'),
        ),
    ]
