# Generated by Django 3.2.4 on 2021-06-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_testimonial_phrase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['id'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзыв(-ов)'},
        ),
    ]
