# Generated by Django 3.2.4 on 2021-06-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.CharField(max_length=255, verbose_name='Пакет')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('allow', models.BooleanField(verbose_name='Доступность')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.item')),
            ],
            options={
                'verbose_name': 'Услуги в пакете',
                'ordering': ['service', 'pack'],
            },
        ),
    ]
