# Generated by Django 3.2.4 on 2021-06-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
