# Generated by Django 3.2.4 on 2021-06-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.CreateModel(
            name='PackPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.CharField(max_length=255, verbose_name='Пакет')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.item')),
            ],
            options={
                'verbose_name': 'Стоимость пакетов',
            },
        ),
    ]
