# Generated by Django 3.2.4 on 2021-06-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210619_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='place',
            field=models.CharField(default=0, max_length=255, verbose_name='Место'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='program',
            field=models.TextField(blank=True, verbose_name='Программа'),
        ),
        migrations.AddField(
            model_name='item',
            name='restrictions',
            field=models.TextField(blank=True, verbose_name='Ограничения'),
        ),
        migrations.AddField(
            model_name='item',
            name='users',
            field=models.IntegerField(default=0, verbose_name='Количество участников'),
            preserve_default=False,
        ),
    ]
