# Generated by Django 3.2.4 on 2021-07-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210720_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.packs'),
        ),
    ]
